In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
messy_timeseries_df = pd.read_csv("messy_timeseries.csv")
messy_timeseries_df

,timestamp,metric_value,site,notes,extra_column_int,extra_column_flag
0,2024-04-28,57.196,A,manual,32,True
1,2025-02-03,82.990,A,ok,73,False
2,2024-12-28,82.219,A,manual,97,True
3,2024-12-02,80.067,C,sensor?,12,False
4,2024-12-25,75.520,B,ok,92,False
...,...,...,...,...,...,...
423,2024-07-30,58.003,A,manual,18,True
424,2024-03-08,58.009,A,ok,22,True
425,2024/02/01,45.117,B,ok,57,False
426,2024-07-15,59.716,A,ok,17,False
427,2024-06-24,53.589,A,sensor?,20,False

- Note you can see the timestamp data is inconsistent (having dashes or slashes).

In [3]:
messy_timeseries_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 428 entries, 0 to 427
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   timestamp          427 non-null    object
 1   metric_value       410 non-null    float64
 2   site               428 non-null    object
 3   notes              428 non-null    object
 4   extra_column_int   428 non-null    int64
 5   extra_column_flag  428 non-null    bool
dtypes: bool(1), float64(1), int64(1), object(3)
memory usage: 17.3+ KB

In [4]:
messy_timeseries_df.head()

    timestamp  metric_value site    notes  extra_column_int  extra_column_flag
0  2024-04-28        57.196    A   manual                32               True
1  2025-02-03        82.990    A       ok                73              False
2  2024-12-28        82.219    A   manual                97               True
3  2024-12-02        80.067    C  sensor?                12              False
4  2024-12-25        75.520    B       ok                92              False

In [5]:
messy_timeseries_df.describe()

       metric_value  extra_column_int
count    410.000000        428.000000
mean      64.849880         46.782710
std       48.391797         28.548032
min     -120.000000          0.000000
25%       54.474750         22.000000
50%       60.392000         45.000000
75%       72.026250         72.000000
max      999.000000         99.000000

- Note: Outlier with the min value being negative.

In [6]:
messy_timeseries_df['site'].value_counts()

A    214
B    130
C     84
Name: site, dtype: int64

In [7]:
messy_timeseries_df['extra_column_int'].value_counts()

32    11
45     9
46     8
28     8
75     8
      ..
51     2
90     1
59     1
54     1
78     1
Name: extra_column_int, Length: 98, dtype: int64

In [8]:
messy_timeseries_df['timestamp'].isna().value_counts()

False    427
True       1
Name: timestamp, dtype: int64

- Note: Missing values for 'timestamp'

In [9]:
messy_timeseries_df.isna().value_counts()

timestamp  metric_value  site   notes  extra_column_int  extra_column_flag
False      False         False  False  False             False                409
           True          False  False  False             False                 18
True       False         False  False  False             False                  1
dtype: int64

- Note: Missing values for 'timestamp' and 'metric_value'

In [10]:
messy_timeseries_df.duplicated().value_counts()

False    428
dtype: int64

In [11]:
messy_timeseries_df['timestamp'].iloc[46]

'not_a_date'

In [12]:
messy_timeseries_df.drop(index=46, inplace=True)
messy_timeseries_df['timestamp'].iloc[46]

'2025-02-15'

Dropped the missing value for 'timestamp'.

In [13]:
messy_timeseries_df['timestamp'].isna().value_counts()

False    426
True       1
Name: timestamp, dtype: int64

In [14]:
messy_timeseries_df.isna().sum()

timestamp             1
metric_value         18
site                  0
notes                 0
extra_column_int      0
extra_column_flag     0
dtype: int64

In [15]:
messy_timeseries_df.dropna(subset=['timestamp'],inplace=True)
messy_timeseries_df.isna().sum()

timestamp             0
metric_value         18
site                  0
notes                 0
extra_column_int      0
extra_column_flag     0
dtype: int64

Drop the row with na value from column 'timestamp'.

In [16]:
messy_timeseries_df['timestamp'] = pd.to_datetime(messy_timeseries_df['timestamp'])
messy_timeseries_df['timestamp'] = messy_timeseries_df['timestamp'].dt.strftime('%Y-%m-%d')
messy_timeseries_df['timestamp'] = pd.to_datetime(messy_timeseries_df['timestamp'])
messy_timeseries_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 426 entries, 0 to 427
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   timestamp          426 non-null    datetime64[ns]
 1   metric_value       408 non-null    float64
 2   site               426 non-null    object
 3   notes              426 non-null    object
 4   extra_column_int   426 non-null    int64
 5   extra_column_flag  426 non-null    bool
dtypes: bool(1), datetime64[ns](1), float64(1), int64(1), object(2)
memory usage: 20.4+ KB

Change the 'timestamp' object type to datetime type. Also, format the datetime in '%Y-%m-%d'.

In [17]:
messy_timeseries_df

,timestamp,metric_value,site,notes,extra_column_int,extra_column_flag
0,2024-04-28,57.196,A,manual,32,True
1,2025-02-03,82.990,A,ok,73,False
2,2024-12-28,82.219,A,manual,97,True
3,2024-12-02,80.067,C,sensor?,12,False
4,2024-12-25,75.520,B,ok,92,False
...,...,...,...,...,...,...
423,2024-07-30,58.003,A,manual,18,True
424,2024-03-08,58.009,A,ok,22,True
425,2024-02-01,45.117,B,ok,57,False
426,2024-07-15,59.716,A,ok,17,False
427,2024-06-24,53.589,A,sensor?,20,False

In [18]:
messy_timeseries_df['metric_value'].isna().sum()

18

In [19]:
avg_metric_value = messy_timeseries_df['metric_value'].mean()
messy_timeseries_df['metric_value'].fillna(avg_metric_value, inplace=True)
messy_timeseries_df['metric_value'].isna().sum()

0

In [20]:
messy_timeseries_df.describe()

       metric_value  extra_column_int
count    426.000000        426.000000
mean      64.896904         46.863850
std       47.465411         28.568024
min     -120.000000          0.000000
25%       55.029500         22.000000
50%       61.334000         45.000000
75%       71.788250         72.000000
max      999.000000         99.000000

Above code I replaced missing 'metric_value' with their avg. 'metric_value'.

In [21]:
# sort data by time
sorted_timeseries_df = messy_timeseries_df.sort_values(by='timestamp')
sorted_timeseries_df

,timestamp,metric_value,site,notes,extra_column_int,extra_column_flag
406,2024-01-01,50.762,B,ok,76,True
263,2024-01-02,48.695,C,ok,23,False
39,2024-01-03,54.412,A,ok,76,False
66,2024-01-04,56.021,B,sensor?,10,False
360,2024-01-05,49.772,A,sensor?,48,False
...,...,...,...,...,...,...
197,2025-02-19,75.107,A,ok,97,False
383,2025-02-20,78.121,A,ok,34,True
55,2025-02-21,79.697,B,sensor?,7,False
143,2025-02-22,77.339,C,ok,37,False
355,2025-02-23,82.136,A,ok,53,True

TODO: Detect outliers using IQR or z-score and decide:
    
    •	Remove them
    •	Cap them (winsorize)
    •	Keep them (with strong justification)

In [22]:
from scipy import stats

In [24]:
# Detect outliers using z-score for metric_value:
sorted_timeseries_df['metric_value_zscore'] = np.abs(stats.zscore(sorted_timeseries_df['metric_value'])) 
outliers_z = sorted_timeseries_df[sorted_timeseries_df['metric_value_zscore'] > 3]
print("Outliers (Z-score):\n", outliers_z)

Outliers (Z-score):
      timestamp  metric_value site    notes  extra_column_int  \
405 2024-03-16         999.0    A       ok                15
8   2024-08-28        -120.0    A  sensor?                60

     extra_column_flag  metric_value_zscore
405              False            19.702798
8                False             3.899983

 - You can tell there are about 19 outliers for metric_value. I decide to remove these outliers. By filtering them out <= 3

In [27]:
# Filter out the outliers:
clean_timeseries_df = sorted_timeseries_df[sorted_timeseries_df['metric_value_zscore'] <= 3]
outliers_z2 = clean_timeseries_df[clean_timeseries_df['metric_value_zscore'] > 3]
print("Outliers (Z-score):\n", outliers_z2)
clean_timeseries_df

Outliers (Z-score):
 Empty DataFrame
Columns: [timestamp, metric_value, site, notes, extra_column_int, extra_column_flag, metric_value_zscore]
Index: []

,timestamp,metric_value,site,notes,extra_column_int,extra_column_flag,metric_value_zscore
406,2024-01-01,50.762,B,ok,76,True,0.298144
263,2024-01-02,48.695,C,ok,23,False,0.341743
39,2024-01-03,54.412,A,ok,76,False,0.221155
66,2024-01-04,56.021,B,sensor?,10,False,0.187217
360,2024-01-05,49.772,A,sensor?,48,False,0.319026
...,...,...,...,...,...,...,...
197,2025-02-19,75.107,A,ok,97,False,0.215359
383,2025-02-20,78.121,A,ok,34,True,0.278932
55,2025-02-21,79.697,B,sensor?,7,False,0.312175
143,2025-02-22,77.339,C,ok,37,False,0.262438
355,2025-02-23,82.136,A,ok,53,True,0.363620

- Most of the zscore values are at the mean.

In [29]:
sns.lineplot(data=clean_timeseries_df, x='timestamp', y='metric_value', hue='site', style='event')
plt.show()

ValueError: Could not interpret value `event` for parameter `style`